# Generated by Django 2.2.3 on 2019-08-13 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=225)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete='cascade', related_name='topics', to='mainforum.Boards')),
                ('creator', models.ForeignKey(on_delete='cascade', related_name='topics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=2000)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete='cascade', related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete='cascade', related_name='posts', to='mainforum.Topics')),
                ('updated_by', models.ForeignKey(on_delete='cascade', related_name='posts_update', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
