# Generated by Django 2.2.3 on 2019-09-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainforum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
