# Generated by Django 2.2.3 on 2019-09-16 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainforum', '0002_topics_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='Created_at',
            new_name='created_at',
        ),
    ]
